#!/bin/bash

# Workshop Chapter 2 - Bash Primer

# 1) Experiment with the uname command, seeing what it prints 
#    on the various operating systems. Rewrite the osdetect.sh 
#    script to use the uname command, possibly with one of its options. 
#    Caution: not all options are available on every operating system.

OS=`uname`
echo Your Operational System is $OS

# 2) Modify the osdetect.sh script to use a function. Put the if/then/else 
#    logic inside the function and then call it from the script. Don’t have 
#    the function itself produce any output. Make the output come from the 
#    main part of the script.

function osdetect () {

if type -t wevtutil &> /dev/null
then
	OS=MSWin
elif type -t scutil &> /dev/null
then
	OS=macOS
else
	OS=Linux
fi
	
}

echo $OS

# 3) Set the permissions on the osdetect.sh script to be executable so that 
#    you can run the script without using bash as the first word on the command
#    line. How do you now invoke the script?

./osdetect.sh
