#!/bin/bash

# Workshop Chapter 1 - Command-Line Primer

# 1) Write a command that executs ifconfig and redirects
#    standard output to a file named ipaddress.txt

ifconfig > ipaddress.txt

# 2) Write a command that executs ifconfig and redirects
#    standard output and appends it to a file named ipaddress.txt

ifconfig >> ipaddress.txt

# 3) Write a command that copies all of the files in the directory
#    /etc/a to the directory /etc/b and redirects the standard error
#    to the file copyerror.log

sudo cp -a /etc/a/. /etc/b/

# 4) Write a command that performs a directory listing ( ls ) on the 
#    root file directory and pipes the output into the more command.

sudo ls /root/ | more

# 5) Write a command that executes mytask.sh and sends it to the background.

./mytask.sh &

# 6) 6. Given the following job list, write the command that brings the Amazon ping
#    task to the foreground:
#    [1]  Running ping www.google.com > /dev/null &
#    [2]- Running ping www.amazon.com > /dev/null &
#    [3]+ Running ping www.amazon.com > /dev/null &

fg 2
